### ISSUE TITLE
How to manage the spot after flash?

### ISSUE THREAD

**Issue by catsado89** [NebraLtd/helium-pycom#4]
Hello,
I have flashed my pycom SD card with this image, but how can I manage the hotspot now? I need to connect it to WiFi but what app should I use?
Thank you.
P.S. Using the nebra app - Update WiFi is not finding the hotspot.

**Comment by shawaj** [comment]
You need to use the Nebra app. You need to do it within the first 5 minutes of turning the hotspot on.

You can also view the diagnostics page by visiting the IP address of the hotspot

**Comment by catsado89** [comment]
The nebra app is not finding the hotspot, so I can't to it. Pycom old app finds it but can't connect. I can't visit the diagnostics page because my hotspot have only WiFi and no LAN port, so in order to connect it to the router I need the nebra app to find the hotspot first. Please Nebra guys assist :( .

**Comment by shawaj** [comment]
What phone are you using?

What version of the Nebra app?

And what version of the Nebra firmware did you flash on it?

**Comment by catsado89** [comment]
Using a android phone - Samsung Galaxy A80 running Android version 11.

The latest version of Nebra Hotspot from the android play store.

The latest here on github - v1.0.2-6-helium-pycom-2023-04-26-OpenFleet

**Comment by shawaj** [comment]
Is the app version 2.0.1?

Can you check on the play store?

**Comment by catsado89** [comment]
Yes indeed version 2.0.1.

**Comment by shawaj** [comment]
@catsado89 can you share some screenshots of where it's going wrong

**Comment by catsado89** [comment]
I have no idea how a screenshot but okey. Here you can see in the first screenshot i select Update WiFi
![1](https://user-images.githubusercontent.com/102851309/236669255-f25c0f8e-3ee3-4a6f-9794-008f55c7773b.jpg)
Then the app starts to scan for a hotspot but finds nothing
![2](https://user-images.githubusercontent.com/102851309/236669277-5eb68927-ebfd-4037-b5f8-1577af385b47.jpg)
But if I scan with the old pycom app it finds the hotspot but can't connect to it.
![3](https://user-images.githubusercontent.com/102851309/236669302-50ae9b15-0c26-488b-a695-daa8786f41ed.jpg)

**Comment by catsado89** [comment]
Flashed the spot SD card with the latest release - v1.0.2-9-helium-pycom-2023-05-09-OpenFleet , still no change the Nebra app dosn't find the device and I can't connect it to the WiFi Router. Please help.

**Comment by shawaj** [comment]
@catsado89 Can you please create a ticket at https://support.nebra.com with a link to this issue here? And can you reply back with the ticket number?

Thanks

**Comment by catsado89** [comment]
Hello again. I have created a ticket - Ticket (#421355) .

**Comment by shawaj** [comment]
@WayneNebra FYI

**Comment by WayneNebra** [comment]
@shawaj OK thanks, will check it out.

**Comment by catsado89** [comment]
Hello? Can I please get any help?

**Comment by WayneNebra** [comment]
@catsado89 Have you updated the App on the Play Store , we just pushed an update 16th May 2023

**Comment by catsado89** [comment]
Indeed I have.

**Comment by WayneNebra** [comment]
Replied on your ticket

**Comment by catsado89** [comment]
Okey so you stopped replying in my ticket, no problem. Your latest version of the app still can't see the hotspot but do you know what app see the hotspot? Hotspotty Connect. Thanks to it I was able to resolve my problem.

**Comment by WayneNebra** [comment]
​Thanks so much for your message, and sorry about the delay in getting back in touch, we've been extremely busy, so I do apologise, I thought you were sending a copy of your JSON file in so I could check it all out from this end, however after reading your message it looks like you've resolved this now? but we'd still like to know why the Nebra App hasn't found the miner. 

You can still access you local diagnostics page, just use the IP address of the miner in your browser. 

I'll send instructions over on the ticket. 

Thanks

**Comment by shawaj** [comment]
Closing as no reply
